/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.xtext.example.domainmodel

import org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageFacade

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DomainmodelRuntimeModule extends AbstractDomainmodelRuntimeModule {
	def bindResourceStorageFacade() { BatchLinkableResourceStorageFacade }
}
